name: flutter_application_kledo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.3.0
  flutter_launcher_icons: ^0.13.1  # <-- Tambahkan ini

flutter:
  uses-material-design: true

  assets:
    #- images/kledo.png
    - assets/image/baru.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/akuntan.jpg"
